### ISSUE TITLE
Release to maven central?

### ISSUE THREAD

**Issue by johanhaleby** [exceptionfactory/socketbroker#1]
Hi, 

Would it be possible to make a release to maven central? That would be really useful :)

Regards,
/Johan

**Comment by johanhaleby** [comment]
Sorry I was too fast, I now see that it's already there. I was confused this I couldn't find it in the docs. But this great! Thank you :)

**Comment by exceptionfactory** [comment]
Thanks for asking @johanhaleby, feel free to follow up if you have any additional feedback on the library.
